@Istest
public class RoomSelectorTest {
   @Istest
    static void RoomSelector(){
       // Create a Unit Of Work
       fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new Schema.SObjectType[] {
                Account.SObjectType,
                Contact.SObjectType,
                room__c.SObjectType
                    }
        );
       Account acc= new Account();
       acc.Name ='Test Account';
       uow.registerNew(acc); 
       // Commit the work to the database!
      
        
       System.assertnotEquals(null,acc);
       Contact con = new Contact(LastName='Test Contact');
      
       //uow.registerRelationship(con, con.AccountId, acc)
       uow.registerNew(con, Contact.AccountId, acc);
      
       System.assertnotEquals(null,con);
       Room__c room = new Room__c ();
       room.Name = 'RM01';
       room.Guest__c = con.id ;
      
      uow.registerNew(room, Room__c.Guest__c, con);
        // Commit the work to the database!
        uow.commitWork();
        
        test.startTest();
        new RoomSelector().selectByRoomId(New Set<id>{room.Id});
        test.stopTest();
    }
    @Istest
    static void RoomSelector2(){
       // Create a Unit Of Work
       fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new Schema.SObjectType[] {
                Account.SObjectType,
                Contact.SObjectType,
                room__c.SObjectType
                    }
        );
       Account acc= new Account();
       acc.Name ='Test Account';
       uow.registerNew(acc); 
      
        
       System.assertnotEquals(null,acc);
       Contact con = new Contact(LastName='Test Contact');
      
       //uow.registernew(con, con.AccountId, acc)
       uow.registerNew(con, Contact.AccountId, acc);
      
       System.assertnotEquals(null,con);
       Room__c room = new Room__c ();
       room.Name = 'RM01';
       //room.Guest__c = con.id ;
       room.Occupied__c =false;
        
       Room__c room2 = new Room__c ();
       room2.Name = 'RM01';
       //room.Guest__c = con.id ;
       room2.Occupied__c =false;
      
       uow.registerNew(room);
       uow.registerNew(room2);
       // Commit the work to the database!
       uow.commitWork();
       room2.Guest__c = con.id ;
       uow.registerDirty(room2);
        
        test.startTest();
        new RoomSelector().selectByRoomId(New Set<id>{room.Id});
        test.stopTest();
    }
}